# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/FOLME_UI.ui'
#
# Created: Mon Jan  9 10:07:36 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QFMC(object):
    def setupUi(self, QFMC):
        QFMC.setObjectName(_fromUtf8("QFMC"))
        QFMC.setWindowModality(QtCore.Qt.WindowModal)
        QFMC.resize(400, 260)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QFMC.sizePolicy().hasHeightForWidth())
        QFMC.setSizePolicy(sizePolicy)
        QFMC.setMinimumSize(QtCore.QSize(400, 260))
        QFMC.setMaximumSize(QtCore.QSize(400, 280))
        QFMC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        QFMC.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtGui.QWidget(QFMC)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.FMCRealname = QtGui.QLabel(self.centralwidget)
        self.FMCRealname.setGeometry(QtCore.QRect(15, 23, 371, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.FMCRealname.setFont(font)
        self.FMCRealname.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FMCRealname.setText(_fromUtf8(""))
        self.FMCRealname.setObjectName(_fromUtf8("FMCRealname"))
        self.VidLabel = QtGui.QLabel(self.centralwidget)
        self.VidLabel.setGeometry(QtCore.QRect(13, 55, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VidLabel.setFont(font)
        self.VidLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VidLabel.setObjectName(_fromUtf8("VidLabel"))
        self.VidText = QtGui.QLabel(self.centralwidget)
        self.VidText.setGeometry(QtCore.QRect(43, 55, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.VidText.setFont(font)
        self.VidText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VidText.setText(_fromUtf8(""))
        self.VidText.setObjectName(_fromUtf8("VidText"))
        self.FMCLabel = QtGui.QLabel(self.centralwidget)
        self.FMCLabel.setGeometry(QtCore.QRect(140, 55, 171, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.FMCLabel.setFont(font)
        self.FMCLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FMCLabel.setObjectName(_fromUtf8("FMCLabel"))
        self.ControllingText = QtGui.QLabel(self.centralwidget)
        self.ControllingText.setGeometry(QtCore.QRect(140, 70, 241, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ControllingText.setFont(font)
        self.ControllingText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ControllingText.setText(_fromUtf8(""))
        self.ControllingText.setObjectName(_fromUtf8("ControllingText"))
        self.Flag = QtGui.QLabel(self.centralwidget)
        self.Flag.setGeometry(QtCore.QRect(307, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Flag.setFont(font)
        self.Flag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Flag.setText(_fromUtf8(""))
        self.Flag.setObjectName(_fromUtf8("Flag"))
        self.TimeOnLineText = QtGui.QLabel(self.centralwidget)
        self.TimeOnLineText.setGeometry(QtCore.QRect(10, 131, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.TimeOnLineText.setFont(font)
        self.TimeOnLineText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TimeOnLineText.setText(_fromUtf8(""))
        self.TimeOnLineText.setObjectName(_fromUtf8("TimeOnLineText"))
        self.SoftwareText = QtGui.QLabel(self.centralwidget)
        self.SoftwareText.setGeometry(QtCore.QRect(74, 162, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SoftwareText.setFont(font)
        self.SoftwareText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SoftwareText.setText(_fromUtf8(""))
        self.SoftwareText.setObjectName(_fromUtf8("SoftwareText"))
        self.ConnectedText = QtGui.QLabel(self.centralwidget)
        self.ConnectedText.setGeometry(QtCore.QRect(338, 162, 31, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ConnectedText.setFont(font)
        self.ConnectedText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConnectedText.setText(_fromUtf8(""))
        self.ConnectedText.setObjectName(_fromUtf8("ConnectedText"))
        self.Close = QtGui.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(200, 201, 99, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.Close.setFont(font)
        self.Close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close.setObjectName(_fromUtf8("Close"))
        self.AddFriend = QtGui.QPushButton(self.centralwidget)
        self.AddFriend.setGeometry(QtCore.QRect(95, 201, 99, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.AddFriend.setFont(font)
        self.AddFriend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddFriend.setObjectName(_fromUtf8("AddFriend"))
        self.SoftwareLabel = QtGui.QLabel(self.centralwidget)
        self.SoftwareLabel.setGeometry(QtCore.QRect(10, 164, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.SoftwareLabel.setFont(font)
        self.SoftwareLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SoftwareLabel.setObjectName(_fromUtf8("SoftwareLabel"))
        self.ConnectedLabel = QtGui.QLabel(self.centralwidget)
        self.ConnectedLabel.setGeometry(QtCore.QRect(250, 162, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ConnectedLabel.setFont(font)
        self.ConnectedLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConnectedLabel.setObjectName(_fromUtf8("ConnectedLabel"))
        self.rating_img = QtGui.QLabel(self.centralwidget)
        self.rating_img.setGeometry(QtCore.QRect(278, 19, 105, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.rating_img.setFont(font)
        self.rating_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rating_img.setText(_fromUtf8(""))
        self.rating_img.setObjectName(_fromUtf8("rating_img"))
        self.FMC = QtGui.QGroupBox(self.centralwidget)
        self.FMC.setGeometry(QtCore.QRect(4, 6, 391, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.FMC.setFont(font)
        self.FMC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FMC.setObjectName(_fromUtf8("FMC"))
        self.Conection = QtGui.QGroupBox(self.centralwidget)
        self.Conection.setGeometry(QtCore.QRect(4, 114, 391, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Conection.setFont(font)
        self.Conection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Conection.setObjectName(_fromUtf8("Conection"))
        QFMC.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(QFMC)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        QFMC.setStatusBar(self.statusBar)

        self.retranslateUi(QFMC)
        QtCore.QObject.connect(self.Close, QtCore.SIGNAL(_fromUtf8("clicked()")), QFMC.close)
        QtCore.QMetaObject.connectSlotsByName(QFMC)

    def retranslateUi(self, QFMC):
        QFMC.setWindowTitle(QtGui.QApplication.translate("QFMC", "Follow Me Car Service", None, QtGui.QApplication.UnicodeUTF8))
        self.VidLabel.setText(QtGui.QApplication.translate("QFMC", "VID", None, QtGui.QApplication.UnicodeUTF8))
        self.FMCLabel.setText(QtGui.QApplication.translate("QFMC", "Follow Me Car Service at", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setText(QtGui.QApplication.translate("QFMC", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.AddFriend.setText(QtGui.QApplication.translate("QFMC", "Add Friend", None, QtGui.QApplication.UnicodeUTF8))
        self.SoftwareLabel.setText(QtGui.QApplication.translate("QFMC", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnectedLabel.setText(QtGui.QApplication.translate("QFMC", "Connected to", None, QtGui.QApplication.UnicodeUTF8))
        self.FMC.setTitle(QtGui.QApplication.translate("QFMC", "FMC Service", None, QtGui.QApplication.UnicodeUTF8))
        self.Conection.setTitle(QtGui.QApplication.translate("QFMC", "Conection", None, QtGui.QApplication.UnicodeUTF8))

