# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/SettingWindow_UI.ui'
#
# Created: Mon Nov  7 10:12:47 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName(_fromUtf8("SettingWindow"))
        SettingWindow.resize(320, 320)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingWindow.sizePolicy().hasHeightForWidth())
        SettingWindow.setSizePolicy(sizePolicy)
        SettingWindow.setMinimumSize(QtCore.QSize(320, 320))
        SettingWindow.setMaximumSize(QtCore.QSize(345, 320))
        SettingWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        SettingWindow.setWindowTitle(QtGui.QApplication.translate("SettingWindow", "Settings of IVAO :: Status", None, QtGui.QApplication.UnicodeUTF8))
        SettingWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(SettingWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SettingAccepButton = QtGui.QPushButton(self.centralwidget)
        self.SettingAccepButton.setGeometry(QtCore.QRect(108, 284, 99, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.SettingAccepButton.setFont(font)
        self.SettingAccepButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SettingAccepButton.setText(QtGui.QApplication.translate("SettingWindow", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.SettingAccepButton.setObjectName(_fromUtf8("SettingAccepButton"))
        self.SettingTimeUpdate = QtGui.QLabel(self.centralwidget)
        self.SettingTimeUpdate.setGeometry(QtCore.QRect(14, 16, 231, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.SettingTimeUpdate.setFont(font)
        self.SettingTimeUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SettingTimeUpdate.setText(QtGui.QApplication.translate("SettingWindow", "Setting Time for Update Info in minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.SettingTimeUpdate.setObjectName(_fromUtf8("SettingTimeUpdate"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(250, 13, 56, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.spinBox.setFont(font)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(60)
        self.spinBox.setSingleStep(5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.Setting_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.Setting_checkBox.setEnabled(True)
        self.Setting_checkBox.setGeometry(QtCore.QRect(14, 121, 85, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.Setting_checkBox.setFont(font)
        self.Setting_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Setting_checkBox.setText(QtGui.QApplication.translate("SettingWindow", "Use Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.Setting_checkBox.setChecked(False)
        self.Setting_checkBox.setTristate(False)
        self.Setting_checkBox.setObjectName(_fromUtf8("Setting_checkBox"))
        self.proxy_host = QtGui.QLabel(self.centralwidget)
        self.proxy_host.setEnabled(True)
        self.proxy_host.setGeometry(QtCore.QRect(20, 154, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.proxy_host.setFont(font)
        self.proxy_host.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proxy_host.setText(QtGui.QApplication.translate("SettingWindow", "Host  http://", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_host.setObjectName(_fromUtf8("proxy_host"))
        self.proxy_port = QtGui.QLabel(self.centralwidget)
        self.proxy_port.setEnabled(True)
        self.proxy_port.setGeometry(QtCore.QRect(60, 178, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.proxy_port.setFont(font)
        self.proxy_port.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proxy_port.setText(QtGui.QApplication.translate("SettingWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_port.setObjectName(_fromUtf8("proxy_port"))
        self.proxy_user = QtGui.QLabel(self.centralwidget)
        self.proxy_user.setEnabled(True)
        self.proxy_user.setGeometry(QtCore.QRect(30, 233, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.proxy_user.setFont(font)
        self.proxy_user.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proxy_user.setText(QtGui.QApplication.translate("SettingWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_user.setObjectName(_fromUtf8("proxy_user"))
        self.proxy_pass = QtGui.QLabel(self.centralwidget)
        self.proxy_pass.setEnabled(True)
        self.proxy_pass.setGeometry(QtCore.QRect(31, 260, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.proxy_pass.setFont(font)
        self.proxy_pass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proxy_pass.setText(QtGui.QApplication.translate("SettingWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_pass.setObjectName(_fromUtf8("proxy_pass"))
        self.Setting_auth = QtGui.QCheckBox(self.centralwidget)
        self.Setting_auth.setEnabled(True)
        self.Setting_auth.setGeometry(QtCore.QRect(14, 205, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.Setting_auth.setFont(font)
        self.Setting_auth.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Setting_auth.setText(QtGui.QApplication.translate("SettingWindow", "Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.Setting_auth.setChecked(False)
        self.Setting_auth.setTristate(False)
        self.Setting_auth.setObjectName(_fromUtf8("Setting_auth"))
        self.lineEdit_host = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_host.setEnabled(True)
        self.lineEdit_host.setGeometry(QtCore.QRect(90, 150, 181, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.lineEdit_host.setFont(font)
        self.lineEdit_host.setObjectName(_fromUtf8("lineEdit_host"))
        self.lineEdit_port = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_port.setEnabled(True)
        self.lineEdit_port.setGeometry(QtCore.QRect(90, 175, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.lineEdit_port.setFont(font)
        self.lineEdit_port.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_port.setInputMask(QtGui.QApplication.translate("SettingWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_port.setMaxLength(5)
        self.lineEdit_port.setObjectName(_fromUtf8("lineEdit_port"))
        self.lineEdit_user = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_user.setEnabled(True)
        self.lineEdit_user.setGeometry(QtCore.QRect(90, 230, 181, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.lineEdit_pass = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_pass.setEnabled(True)
        self.lineEdit_pass.setGeometry(QtCore.QRect(90, 256, 181, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_pass.setObjectName(_fromUtf8("lineEdit_pass"))
        self.AutoRefreshMap = QtGui.QCheckBox(self.centralwidget)
        self.AutoRefreshMap.setGeometry(QtCore.QRect(14, 40, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.AutoRefreshMap.setFont(font)
        self.AutoRefreshMap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AutoRefreshMap.setText(QtGui.QApplication.translate("SettingWindow", "Auto-Refresh the map when connecting to IVAO", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoRefreshMap.setChecked(True)
        self.AutoRefreshMap.setTristate(False)
        self.AutoRefreshMap.setObjectName(_fromUtf8("AutoRefreshMap"))
        self.ShowLabelPilots = QtGui.QCheckBox(self.centralwidget)
        self.ShowLabelPilots.setGeometry(QtCore.QRect(14, 65, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.ShowLabelPilots.setFont(font)
        self.ShowLabelPilots.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ShowLabelPilots.setText(QtGui.QApplication.translate("SettingWindow", "Show Label of Pilots", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowLabelPilots.setChecked(True)
        self.ShowLabelPilots.setTristate(False)
        self.ShowLabelPilots.setObjectName(_fromUtf8("ShowLabelPilots"))
        self.ShowLabelControllers = QtGui.QCheckBox(self.centralwidget)
        self.ShowLabelControllers.setGeometry(QtCore.QRect(14, 90, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.ShowLabelControllers.setFont(font)
        self.ShowLabelControllers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ShowLabelControllers.setText(QtGui.QApplication.translate("SettingWindow", "Show Label of Controllers", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowLabelControllers.setChecked(True)
        self.ShowLabelControllers.setTristate(False)
        self.ShowLabelControllers.setObjectName(_fromUtf8("ShowLabelControllers"))
        SettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        pass

