# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/ControllerInfo_UI.ui'
#
# Created: Mon Nov  7 03:42:30 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QControllerInfo(object):
    def setupUi(self, QControllerInfo):
        QControllerInfo.setObjectName(_fromUtf8("QControllerInfo"))
        QControllerInfo.setWindowModality(QtCore.Qt.WindowModal)
        QControllerInfo.resize(400, 437)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QControllerInfo.sizePolicy().hasHeightForWidth())
        QControllerInfo.setSizePolicy(sizePolicy)
        QControllerInfo.setMinimumSize(QtCore.QSize(400, 437))
        QControllerInfo.setMaximumSize(QtCore.QSize(400, 437))
        QControllerInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        QControllerInfo.setFocusPolicy(QtCore.Qt.StrongFocus)
        QControllerInfo.setWindowTitle(QtGui.QApplication.translate("QControllerInfo", "Controller Info", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(QControllerInfo)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ControllerText = QtGui.QLabel(self.centralwidget)
        self.ControllerText.setGeometry(QtCore.QRect(15, 22, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ControllerText.setFont(font)
        self.ControllerText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ControllerText.setText(_fromUtf8(""))
        self.ControllerText.setObjectName(_fromUtf8("ControllerText"))
        self.VidLabel = QtGui.QLabel(self.centralwidget)
        self.VidLabel.setGeometry(QtCore.QRect(13, 55, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VidLabel.setFont(font)
        self.VidLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VidLabel.setText(QtGui.QApplication.translate("QControllerInfo", "VID", None, QtGui.QApplication.UnicodeUTF8))
        self.VidLabel.setObjectName(_fromUtf8("VidLabel"))
        self.VidText = QtGui.QLabel(self.centralwidget)
        self.VidText.setGeometry(QtCore.QRect(43, 55, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.VidText.setFont(font)
        self.VidText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VidText.setText(_fromUtf8(""))
        self.VidText.setObjectName(_fromUtf8("VidText"))
        self.ControllingLabel = QtGui.QLabel(self.centralwidget)
        self.ControllingLabel.setGeometry(QtCore.QRect(140, 55, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ControllingLabel.setFont(font)
        self.ControllingLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ControllingLabel.setText(QtGui.QApplication.translate("QControllerInfo", "Controlling in ", None, QtGui.QApplication.UnicodeUTF8))
        self.ControllingLabel.setObjectName(_fromUtf8("ControllingLabel"))
        self.ControllingText = QtGui.QLabel(self.centralwidget)
        self.ControllingText.setGeometry(QtCore.QRect(140, 70, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ControllingText.setFont(font)
        self.ControllingText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ControllingText.setText(_fromUtf8(""))
        self.ControllingText.setObjectName(_fromUtf8("ControllingText"))
        self.Flag = QtGui.QLabel(self.centralwidget)
        self.Flag.setGeometry(QtCore.QRect(234, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Flag.setFont(font)
        self.Flag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Flag.setText(_fromUtf8(""))
        self.Flag.setObjectName(_fromUtf8("Flag"))
        self.facility_freq_Text = QtGui.QLabel(self.centralwidget)
        self.facility_freq_Text.setGeometry(QtCore.QRect(13, 124, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.facility_freq_Text.setFont(font)
        self.facility_freq_Text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.facility_freq_Text.setText(_fromUtf8(""))
        self.facility_freq_Text.setObjectName(_fromUtf8("facility_freq_Text"))
        self.ATISInfo = QtGui.QTextEdit(self.centralwidget)
        self.ATISInfo.setGeometry(QtCore.QRect(9, 149, 380, 145))
        self.ATISInfo.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ATISInfo.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.ATISInfo.setReadOnly(True)
        self.ATISInfo.setAcceptRichText(False)
        self.ATISInfo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ATISInfo.setObjectName(_fromUtf8("ATISInfo"))
        self.TimeOnLineText = QtGui.QLabel(self.centralwidget)
        self.TimeOnLineText.setGeometry(QtCore.QRect(10, 320, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.TimeOnLineText.setFont(font)
        self.TimeOnLineText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TimeOnLineText.setText(_fromUtf8(""))
        self.TimeOnLineText.setObjectName(_fromUtf8("TimeOnLineText"))
        self.SoftwareText = QtGui.QLabel(self.centralwidget)
        self.SoftwareText.setGeometry(QtCore.QRect(74, 351, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SoftwareText.setFont(font)
        self.SoftwareText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SoftwareText.setText(_fromUtf8(""))
        self.SoftwareText.setObjectName(_fromUtf8("SoftwareText"))
        self.ConnectedText = QtGui.QLabel(self.centralwidget)
        self.ConnectedText.setGeometry(QtCore.QRect(330, 351, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ConnectedText.setFont(font)
        self.ConnectedText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConnectedText.setText(_fromUtf8(""))
        self.ConnectedText.setObjectName(_fromUtf8("ConnectedText"))
        self.Close = QtGui.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(200, 390, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Close.setFont(font)
        self.Close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close.setText(QtGui.QApplication.translate("QControllerInfo", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setObjectName(_fromUtf8("Close"))
        self.AddFriend = QtGui.QPushButton(self.centralwidget)
        self.AddFriend.setGeometry(QtCore.QRect(95, 390, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AddFriend.setFont(font)
        self.AddFriend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddFriend.setText(QtGui.QApplication.translate("QControllerInfo", "Add Friend", None, QtGui.QApplication.UnicodeUTF8))
        self.AddFriend.setObjectName(_fromUtf8("AddFriend"))
        self.SoftwareLabel = QtGui.QLabel(self.centralwidget)
        self.SoftwareLabel.setGeometry(QtCore.QRect(10, 353, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.SoftwareLabel.setFont(font)
        self.SoftwareLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SoftwareLabel.setText(QtGui.QApplication.translate("QControllerInfo", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.SoftwareLabel.setObjectName(_fromUtf8("SoftwareLabel"))
        self.ConnectedLabel = QtGui.QLabel(self.centralwidget)
        self.ConnectedLabel.setGeometry(QtCore.QRect(250, 351, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ConnectedLabel.setFont(font)
        self.ConnectedLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ConnectedLabel.setText(QtGui.QApplication.translate("QControllerInfo", "Connected to", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnectedLabel.setObjectName(_fromUtf8("ConnectedLabel"))
        self.rating_img = QtGui.QLabel(self.centralwidget)
        self.rating_img.setGeometry(QtCore.QRect(278, 19, 105, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rating_img.setFont(font)
        self.rating_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rating_img.setText(_fromUtf8(""))
        self.rating_img.setObjectName(_fromUtf8("rating_img"))
        self.Controller = QtGui.QGroupBox(self.centralwidget)
        self.Controller.setGeometry(QtCore.QRect(4, 6, 391, 95))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Controller.setFont(font)
        self.Controller.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Controller.setTitle(QtGui.QApplication.translate("QControllerInfo", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.Controller.setObjectName(_fromUtf8("Controller"))
        self.FacilityDetails = QtGui.QGroupBox(self.centralwidget)
        self.FacilityDetails.setGeometry(QtCore.QRect(4, 110, 391, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.FacilityDetails.setFont(font)
        self.FacilityDetails.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FacilityDetails.setTitle(QtGui.QApplication.translate("QControllerInfo", "Facility Details", None, QtGui.QApplication.UnicodeUTF8))
        self.FacilityDetails.setObjectName(_fromUtf8("FacilityDetails"))
        self.Conection = QtGui.QGroupBox(self.centralwidget)
        self.Conection.setGeometry(QtCore.QRect(4, 303, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Conection.setFont(font)
        self.Conection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Conection.setTitle(QtGui.QApplication.translate("QControllerInfo", "Conection", None, QtGui.QApplication.UnicodeUTF8))
        self.Conection.setObjectName(_fromUtf8("Conection"))
        QControllerInfo.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(QControllerInfo)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        QControllerInfo.setStatusBar(self.statusBar)

        self.retranslateUi(QControllerInfo)
        QtCore.QObject.connect(self.Close, QtCore.SIGNAL(_fromUtf8("clicked()")), QControllerInfo.close)
        QtCore.QMetaObject.connectSlotsByName(QControllerInfo)

    def retranslateUi(self, QControllerInfo):
        pass

