# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/MainWindow_UI.ui'
#
# Created: Thu Jul 28 16:29:04 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtCore.Qt.PointingHandCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(4, 30, 1015, 711))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.main = QtGui.QWidget()
        self.main.setObjectName(_fromUtf8("main"))
        self.TotalPlayers = QtGui.QLineEdit(self.main)
        self.TotalPlayers.setEnabled(True)
        self.TotalPlayers.setGeometry(QtCore.QRect(92, 657, 51, 23))
        self.TotalPlayers.setReadOnly(True)
        self.TotalPlayers.setObjectName(_fromUtf8("TotalPlayers"))
        self.TotalATC = QtGui.QLineEdit(self.main)
        self.TotalATC.setEnabled(True)
        self.TotalATC.setGeometry(QtCore.QRect(202, 656, 51, 23))
        self.TotalATC.setReadOnly(True)
        self.TotalATC.setObjectName(_fromUtf8("TotalATC"))
        self.TotalPilots = QtGui.QLineEdit(self.main)
        self.TotalPilots.setEnabled(True)
        self.TotalPilots.setGeometry(QtCore.QRect(320, 656, 51, 23))
        self.TotalPilots.setReadOnly(True)
        self.TotalPilots.setObjectName(_fromUtf8("TotalPilots"))
        self.TotalPlayers_label = QtGui.QLabel(self.main)
        self.TotalPlayers_label.setGeometry(QtCore.QRect(19, 660, 71, 20))
        self.TotalPlayers_label.setObjectName(_fromUtf8("TotalPlayers_label"))
        self.TotalAtc_label = QtGui.QLabel(self.main)
        self.TotalAtc_label.setGeometry(QtCore.QRect(176, 660, 31, 20))
        self.TotalAtc_label.setObjectName(_fromUtf8("TotalAtc_label"))
        self.TotalPilots_label = QtGui.QLabel(self.main)
        self.TotalPilots_label.setGeometry(QtCore.QRect(282, 660, 41, 20))
        self.TotalPilots_label.setObjectName(_fromUtf8("TotalPilots_label"))
        self.IVAOStatustableView = QtGui.QTableView(self.main)
        self.IVAOStatustableView.setGeometry(QtCore.QRect(9, 22, 441, 211))
        self.IVAOStatustableView.setObjectName(_fromUtf8("IVAOStatustableView"))
        self.IVAOStatusLabel = QtGui.QLabel(self.main)
        self.IVAOStatusLabel.setGeometry(QtCore.QRect(11, 5, 71, 16))
        self.IVAOStatusLabel.setObjectName(_fromUtf8("IVAOStatusLabel"))
        self.FriendstableWidget = QtGui.QTableWidget(self.main)
        self.FriendstableWidget.setGeometry(QtCore.QRect(470, 23, 531, 211))
        self.FriendstableWidget.setObjectName(_fromUtf8("FriendstableWidget"))
        self.FriendstableWidget.setColumnCount(0)
        self.FriendstableWidget.setRowCount(0)
        self.FriendsLabel = QtGui.QLabel(self.main)
        self.FriendsLabel.setGeometry(QtCore.QRect(470, 6, 51, 16))
        self.FriendsLabel.setObjectName(_fromUtf8("FriendsLabel"))
        self.SearchClientsLabel = QtGui.QLabel(self.main)
        self.SearchClientsLabel.setGeometry(QtCore.QRect(13, 254, 91, 16))
        self.SearchClientsLabel.setObjectName(_fromUtf8("SearchClientsLabel"))
        self.SearchtableWidget = QtGui.QTableWidget(self.main)
        self.SearchtableWidget.setGeometry(QtCore.QRect(10, 292, 441, 211))
        self.SearchtableWidget.setObjectName(_fromUtf8("SearchtableWidget"))
        self.SearchtableWidget.setColumnCount(0)
        self.SearchtableWidget.setRowCount(0)
        self.SearchForLabel = QtGui.QLabel(self.main)
        self.SearchForLabel.setGeometry(QtCore.QRect(13, 273, 81, 16))
        self.SearchForLabel.setObjectName(_fromUtf8("SearchForLabel"))
        self.METARtableWidget = QtGui.QTableWidget(self.main)
        self.METARtableWidget.setGeometry(QtCore.QRect(470, 291, 531, 211))
        self.METARtableWidget.setObjectName(_fromUtf8("METARtableWidget"))
        self.METARtableWidget.setColumnCount(0)
        self.METARtableWidget.setRowCount(0)
        self.MetarLabel = QtGui.QLabel(self.main)
        self.MetarLabel.setGeometry(QtCore.QRect(473, 272, 81, 16))
        self.MetarLabel.setObjectName(_fromUtf8("MetarLabel"))
        self.SearchcomboBox = QtGui.QComboBox(self.main)
        self.SearchcomboBox.setGeometry(QtCore.QRect(90, 270, 80, 20))
        self.SearchcomboBox.setObjectName(_fromUtf8("SearchcomboBox"))
        self.SearchcomboBox.addItem(_fromUtf8(""))
        self.SearchcomboBox.addItem(_fromUtf8(""))
        self.SearchcomboBox.addItem(_fromUtf8(""))
        self.SearchEdit = QtGui.QLineEdit(self.main)
        self.SearchEdit.setGeometry(QtCore.QRect(170, 270, 113, 20))
        self.SearchEdit.setObjectName(_fromUtf8("SearchEdit"))
        self.METAREdit = QtGui.QLineEdit(self.main)
        self.METAREdit.setGeometry(QtCore.QRect(520, 270, 61, 20))
        self.METAREdit.setObjectName(_fromUtf8("METAREdit"))
        self.tabWidget.addTab(self.main, _fromUtf8(""))
        self.countries = QtGui.QWidget()
        self.countries.setObjectName(_fromUtf8("countries"))
        self.country_list = QtGui.QComboBox(self.countries)
        self.country_list.setGeometry(QtCore.QRect(9, 6, 215, 20))
        self.country_list.setObjectName(_fromUtf8("country_list"))
        self.ATCtableView = QtGui.QTableView(self.countries)
        self.ATCtableView.setGeometry(QtCore.QRect(8, 30, 991, 161))
        self.ATCtableView.setObjectName(_fromUtf8("ATCtableView"))
        self.PilottableView = QtGui.QTableView(self.countries)
        self.PilottableView.setGeometry(QtCore.QRect(8, 210, 991, 471))
        self.PilottableView.setObjectName(_fromUtf8("PilottableView"))
        self.atc_label = QtGui.QLabel(self.countries)
        self.atc_label.setGeometry(QtCore.QRect(535, 13, 51, 16))
        self.atc_label.setObjectName(_fromUtf8("atc_label"))
        self.pilot_list = QtGui.QLabel(self.countries)
        self.pilot_list.setGeometry(QtCore.QRect(530, 193, 61, 16))
        self.pilot_list.setObjectName(_fromUtf8("pilot_list"))
        self.tabWidget.addTab(self.countries, _fromUtf8(""))
        self.controllers = QtGui.QWidget()
        self.controllers.setObjectName(_fromUtf8("controllers"))
        self.ATC_FullList = QtGui.QTableView(self.controllers)
        self.ATC_FullList.setGeometry(QtCore.QRect(0, 0, 1006, 683))
        self.ATC_FullList.setObjectName(_fromUtf8("ATC_FullList"))
        self.tabWidget.addTab(self.controllers, _fromUtf8(""))
        self.pilots = QtGui.QWidget()
        self.pilots.setObjectName(_fromUtf8("pilots"))
        self.PILOT_FullList = QtGui.QTableView(self.pilots)
        self.PILOT_FullList.setGeometry(QtCore.QRect(0, 0, 1006, 687))
        self.PILOT_FullList.setObjectName(_fromUtf8("PILOT_FullList"))
        self.tabWidget.addTab(self.pilots, _fromUtf8(""))
        self.observers = QtGui.QWidget()
        self.observers.setObjectName(_fromUtf8("observers"))
        self.ObservertableView = QtGui.QTableView(self.observers)
        self.ObservertableView.setGeometry(QtCore.QRect(10, 10, 991, 661))
        self.ObservertableView.setObjectName(_fromUtf8("ObservertableView"))
        self.tabWidget.addTab(self.observers, _fromUtf8(""))
        self.database = QtGui.QWidget()
        self.database.setObjectName(_fromUtf8("database"))
        self.tableView = QtGui.QTableView(self.database)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 481, 641))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView_2 = QtGui.QTableView(self.database)
        self.tableView_2.setGeometry(QtCore.QRect(500, 40, 501, 641))
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.tabWidget.addTab(self.database, _fromUtf8(""))
        self.actual_user = QtGui.QWidget()
        self.actual_user.setObjectName(_fromUtf8("actual_user"))
        self.InboundTableView = QtGui.QTableView(self.actual_user)
        self.InboundTableView.setGeometry(QtCore.QRect(0, 20, 1006, 193))
        self.InboundTableView.setObjectName(_fromUtf8("InboundTableView"))
        self.Inbound_traffic = QtGui.QLabel(self.actual_user)
        self.Inbound_traffic.setGeometry(QtCore.QRect(444, 4, 91, 20))
        self.Inbound_traffic.setObjectName(_fromUtf8("Inbound_traffic"))
        self.OutboundTableView = QtGui.QTableView(self.actual_user)
        self.OutboundTableView.setGeometry(QtCore.QRect(0, 227, 1006, 192))
        self.OutboundTableView.setObjectName(_fromUtf8("OutboundTableView"))
        self.outbound_traffic = QtGui.QLabel(self.actual_user)
        self.outbound_traffic.setGeometry(QtCore.QRect(444, 211, 101, 20))
        self.outbound_traffic.setObjectName(_fromUtf8("outbound_traffic"))
        self.NearbyATCViewTable = QtGui.QTableView(self.actual_user)
        self.NearbyATCViewTable.setGeometry(QtCore.QRect(0, 435, 1006, 192))
        self.NearbyATCViewTable.setObjectName(_fromUtf8("NearbyATCViewTable"))
        self.nearby_controllers = QtGui.QLabel(self.actual_user)
        self.nearby_controllers.setGeometry(QtCore.QRect(434, 419, 111, 20))
        self.nearby_controllers.setObjectName(_fromUtf8("nearby_controllers"))
        self.tabWidget.addTab(self.actual_user, _fromUtf8(""))
        self.UpdateBtn = QtGui.QPushButton(self.centralwidget)
        self.UpdateBtn.setGeometry(QtCore.QRect(7, 3, 92, 24))
        self.UpdateBtn.setObjectName(_fromUtf8("UpdateBtn"))
        self.ExitBtn = QtGui.QPushButton(self.centralwidget)
        self.ExitBtn.setGeometry(QtCore.QRect(107, 3, 92, 24))
        self.ExitBtn.setObjectName(_fromUtf8("ExitBtn"))
        self.action_update = QtGui.QLabel(self.centralwidget)
        self.action_update.setGeometry(QtCore.QRect(10, 747, 101, 16))
        self.action_update.setObjectName(_fromUtf8("action_update"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.country_list.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IVAO :: Status of IVAN", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPlayers.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalATC.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPilots.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPlayers_label.setText(QtGui.QApplication.translate("MainWindow", "Total Players", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalAtc_label.setText(QtGui.QApplication.translate("MainWindow", "ATC", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPilots_label.setText(QtGui.QApplication.translate("MainWindow", "Pilots", None, QtGui.QApplication.UnicodeUTF8))
        self.IVAOStatusLabel.setText(QtGui.QApplication.translate("MainWindow", "IVAO Status", None, QtGui.QApplication.UnicodeUTF8))
        self.FriendsLabel.setText(QtGui.QApplication.translate("MainWindow", "Friends", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchClientsLabel.setText(QtGui.QApplication.translate("MainWindow", "Search Clients", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchForLabel.setText(QtGui.QApplication.translate("MainWindow", "Search For:", None, QtGui.QApplication.UnicodeUTF8))
        self.MetarLabel.setText(QtGui.QApplication.translate("MainWindow", "METAR", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchcomboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "CallSign", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchcomboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "VID", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchcomboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), QtGui.QApplication.translate("MainWindow", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.atc_label.setText(QtGui.QApplication.translate("MainWindow", "ATC List", None, QtGui.QApplication.UnicodeUTF8))
        self.pilot_list.setText(QtGui.QApplication.translate("MainWindow", "PILOT List", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.countries), QtGui.QApplication.translate("MainWindow", "Countries", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controllers), QtGui.QApplication.translate("MainWindow", "Controllers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pilots), QtGui.QApplication.translate("MainWindow", "Pilots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.observers), QtGui.QApplication.translate("MainWindow", "Observers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.database), QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.Inbound_traffic.setText(QtGui.QApplication.translate("MainWindow", "Inbound Traffic", None, QtGui.QApplication.UnicodeUTF8))
        self.outbound_traffic.setText(QtGui.QApplication.translate("MainWindow", "Outbound Traffic", None, QtGui.QApplication.UnicodeUTF8))
        self.nearby_controllers.setText(QtGui.QApplication.translate("MainWindow", "Nearby Controllers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actual_user), QtGui.QApplication.translate("MainWindow", "Actual User", None, QtGui.QApplication.UnicodeUTF8))
        self.UpdateBtn.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.ExitBtn.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_update.setText(QtGui.QApplication.translate("MainWindow", "Ready", None, QtGui.QApplication.UnicodeUTF8))

