# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/MainWindow_UI.ui'
#
# Created: Wed Jul 27 10:06:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtCore.Qt.PointingHandCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(4, 30, 1015, 711))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.main = QtGui.QWidget()
        self.main.setObjectName(_fromUtf8("main"))
        self.TotalPlayers = QtGui.QLineEdit(self.main)
        self.TotalPlayers.setEnabled(True)
        self.TotalPlayers.setGeometry(QtCore.QRect(29, 20, 51, 23))
        self.TotalPlayers.setReadOnly(True)
        self.TotalPlayers.setObjectName(_fromUtf8("TotalPlayers"))
        self.TotalATC = QtGui.QLineEdit(self.main)
        self.TotalATC.setEnabled(True)
        self.TotalATC.setGeometry(QtCore.QRect(101, 20, 51, 23))
        self.TotalATC.setReadOnly(True)
        self.TotalATC.setObjectName(_fromUtf8("TotalATC"))
        self.TotalPilots = QtGui.QLineEdit(self.main)
        self.TotalPilots.setEnabled(True)
        self.TotalPilots.setGeometry(QtCore.QRect(171, 20, 51, 23))
        self.TotalPilots.setReadOnly(True)
        self.TotalPilots.setObjectName(_fromUtf8("TotalPilots"))
        self.TotalPlayers_label = QtGui.QLabel(self.main)
        self.TotalPlayers_label.setGeometry(QtCore.QRect(18, 40, 71, 20))
        self.TotalPlayers_label.setObjectName(_fromUtf8("TotalPlayers_label"))
        self.TotalAtc_label = QtGui.QLabel(self.main)
        self.TotalAtc_label.setGeometry(QtCore.QRect(114, 40, 31, 20))
        self.TotalAtc_label.setObjectName(_fromUtf8("TotalAtc_label"))
        self.TotalPilots_label = QtGui.QLabel(self.main)
        self.TotalPilots_label.setGeometry(QtCore.QRect(180, 40, 41, 20))
        self.TotalPilots_label.setObjectName(_fromUtf8("TotalPilots_label"))
        self.tabWidget.addTab(self.main, _fromUtf8(""))
        self.countries = QtGui.QWidget()
        self.countries.setObjectName(_fromUtf8("countries"))
        self.country_list = QtGui.QComboBox(self.countries)
        self.country_list.setGeometry(QtCore.QRect(11, 4, 111, 24))
        self.country_list.setObjectName(_fromUtf8("country_list"))
        self.country_list.addItem(_fromUtf8(""))
        self.ATCtableView = QtGui.QTableView(self.countries)
        self.ATCtableView.setGeometry(QtCore.QRect(8, 30, 991, 161))
        self.ATCtableView.setObjectName(_fromUtf8("ATCtableView"))
        self.PilottableView = QtGui.QTableView(self.countries)
        self.PilottableView.setGeometry(QtCore.QRect(8, 210, 991, 471))
        self.PilottableView.setObjectName(_fromUtf8("PilottableView"))
        self.atc_label = QtGui.QLabel(self.countries)
        self.atc_label.setGeometry(QtCore.QRect(535, 13, 41, 16))
        self.atc_label.setObjectName(_fromUtf8("atc_label"))
        self.pilot_list = QtGui.QLabel(self.countries)
        self.pilot_list.setGeometry(QtCore.QRect(530, 193, 61, 16))
        self.pilot_list.setObjectName(_fromUtf8("pilot_list"))
        self.tabWidget.addTab(self.countries, _fromUtf8(""))
        self.controllers = QtGui.QWidget()
        self.controllers.setObjectName(_fromUtf8("controllers"))
        self.ATC_FullList = QtGui.QTableView(self.controllers)
        self.ATC_FullList.setGeometry(QtCore.QRect(0, 0, 1006, 683))
        self.ATC_FullList.setObjectName(_fromUtf8("ATC_FullList"))
        self.tabWidget.addTab(self.controllers, _fromUtf8(""))
        self.pilots = QtGui.QWidget()
        self.pilots.setObjectName(_fromUtf8("pilots"))
        self.PILOT_FullList = QtGui.QTableView(self.pilots)
        self.PILOT_FullList.setGeometry(QtCore.QRect(0, 0, 1006, 687))
        self.PILOT_FullList.setObjectName(_fromUtf8("PILOT_FullList"))
        self.tabWidget.addTab(self.pilots, _fromUtf8(""))
        self.observers = QtGui.QWidget()
        self.observers.setObjectName(_fromUtf8("observers"))
        self.tabWidget.addTab(self.observers, _fromUtf8(""))
        self.database = QtGui.QWidget()
        self.database.setObjectName(_fromUtf8("database"))
        self.tabWidget.addTab(self.database, _fromUtf8(""))
        self.actual_user = QtGui.QWidget()
        self.actual_user.setObjectName(_fromUtf8("actual_user"))
        self.InboundTableView = QtGui.QTableView(self.actual_user)
        self.InboundTableView.setGeometry(QtCore.QRect(0, 20, 1006, 193))
        self.InboundTableView.setObjectName(_fromUtf8("InboundTableView"))
        self.Inbound_traffic = QtGui.QLabel(self.actual_user)
        self.Inbound_traffic.setGeometry(QtCore.QRect(444, 4, 91, 20))
        self.Inbound_traffic.setObjectName(_fromUtf8("Inbound_traffic"))
        self.OutboundTableView = QtGui.QTableView(self.actual_user)
        self.OutboundTableView.setGeometry(QtCore.QRect(0, 227, 1006, 192))
        self.OutboundTableView.setObjectName(_fromUtf8("OutboundTableView"))
        self.outbound_traffic = QtGui.QLabel(self.actual_user)
        self.outbound_traffic.setGeometry(QtCore.QRect(444, 211, 101, 20))
        self.outbound_traffic.setObjectName(_fromUtf8("outbound_traffic"))
        self.NearbyATCViewTable = QtGui.QTableView(self.actual_user)
        self.NearbyATCViewTable.setGeometry(QtCore.QRect(0, 435, 1006, 192))
        self.NearbyATCViewTable.setObjectName(_fromUtf8("NearbyATCViewTable"))
        self.nearby_controllers = QtGui.QLabel(self.actual_user)
        self.nearby_controllers.setGeometry(QtCore.QRect(434, 419, 111, 20))
        self.nearby_controllers.setObjectName(_fromUtf8("nearby_controllers"))
        self.tabWidget.addTab(self.actual_user, _fromUtf8(""))
        self.UpdateBtn = QtGui.QPushButton(self.centralwidget)
        self.UpdateBtn.setGeometry(QtCore.QRect(7, 3, 92, 24))
        self.UpdateBtn.setObjectName(_fromUtf8("UpdateBtn"))
        self.ExitBtn = QtGui.QPushButton(self.centralwidget)
        self.ExitBtn.setGeometry(QtCore.QRect(107, 3, 92, 24))
        self.ExitBtn.setObjectName(_fromUtf8("ExitBtn"))
        self.action_update = QtGui.QLabel(self.centralwidget)
        self.action_update.setGeometry(QtCore.QRect(10, 747, 101, 16))
        self.action_update.setObjectName(_fromUtf8("action_update"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.country_list.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IVAO :: Status of IVAN", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPlayers.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalATC.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPilots.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPlayers_label.setText(QtGui.QApplication.translate("MainWindow", "Total Players", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalAtc_label.setText(QtGui.QApplication.translate("MainWindow", "ATC", None, QtGui.QApplication.UnicodeUTF8))
        self.TotalPilots_label.setText(QtGui.QApplication.translate("MainWindow", "Pilots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), QtGui.QApplication.translate("MainWindow", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.country_list.setItemText(0, QtGui.QApplication.translate("MainWindow", "Cuba", None, QtGui.QApplication.UnicodeUTF8))
        self.atc_label.setText(QtGui.QApplication.translate("MainWindow", "ATC List", None, QtGui.QApplication.UnicodeUTF8))
        self.pilot_list.setText(QtGui.QApplication.translate("MainWindow", "PILOT List", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.countries), QtGui.QApplication.translate("MainWindow", "Countries", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controllers), QtGui.QApplication.translate("MainWindow", "Controllers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pilots), QtGui.QApplication.translate("MainWindow", "Pilots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.observers), QtGui.QApplication.translate("MainWindow", "Observers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.database), QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.Inbound_traffic.setText(QtGui.QApplication.translate("MainWindow", "Inbound Traffic", None, QtGui.QApplication.UnicodeUTF8))
        self.outbound_traffic.setText(QtGui.QApplication.translate("MainWindow", "Outbound Traffic", None, QtGui.QApplication.UnicodeUTF8))
        self.nearby_controllers.setText(QtGui.QApplication.translate("MainWindow", "Nearby Controllers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actual_user), QtGui.QApplication.translate("MainWindow", "Actual User", None, QtGui.QApplication.UnicodeUTF8))
        self.UpdateBtn.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.ExitBtn.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_update.setText(QtGui.QApplication.translate("MainWindow", "Ready", None, QtGui.QApplication.UnicodeUTF8))

