# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/PilotInfo_UI.ui'
#
# Created: Mon Nov  7 13:09:19 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QPilotInfo(object):
    def setupUi(self, QPilotInfo):
        QPilotInfo.setObjectName(_fromUtf8("QPilotInfo"))
        QPilotInfo.setWindowModality(QtCore.Qt.WindowModal)
        QPilotInfo.resize(500, 560)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QPilotInfo.sizePolicy().hasHeightForWidth())
        QPilotInfo.setSizePolicy(sizePolicy)
        QPilotInfo.setMinimumSize(QtCore.QSize(500, 560))
        QPilotInfo.setMaximumSize(QtCore.QSize(500, 560))
        QPilotInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        QPilotInfo.setFocusPolicy(QtCore.Qt.StrongFocus)
        QPilotInfo.setWindowTitle(QtGui.QApplication.translate("QPilotInfo", "Flight Info", None, QtGui.QApplication.UnicodeUTF8))
        QPilotInfo.setDockOptions(QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(QPilotInfo)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.callsign_label = QtGui.QLabel(self.centralwidget)
        self.callsign_label.setGeometry(QtCore.QRect(13, 55, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.callsign_label.setFont(font)
        self.callsign_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.callsign_label.setText(QtGui.QApplication.translate("QPilotInfo", "Callsign", None, QtGui.QApplication.UnicodeUTF8))
        self.callsign_label.setObjectName(_fromUtf8("callsign_label"))
        self.callsign_text = QtGui.QLabel(self.centralwidget)
        self.callsign_text.setGeometry(QtCore.QRect(70, 53, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.callsign_text.setFont(font)
        self.callsign_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.callsign_text.setText(_fromUtf8(""))
        self.callsign_text.setObjectName(_fromUtf8("callsign_text"))
        self.rating_img = QtGui.QLabel(self.centralwidget)
        self.rating_img.setGeometry(QtCore.QRect(360, 49, 121, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.rating_img.setFont(font)
        self.rating_img.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rating_img.setText(_fromUtf8(""))
        self.rating_img.setObjectName(_fromUtf8("rating_img"))
        self.rating_label = QtGui.QLabel(self.centralwidget)
        self.rating_label.setGeometry(QtCore.QRect(314, 53, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.rating_label.setFont(font)
        self.rating_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rating_label.setText(QtGui.QApplication.translate("QPilotInfo", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.rating_label.setObjectName(_fromUtf8("rating_label"))
        self.progressBarTrack = QtGui.QProgressBar(self.centralwidget)
        self.progressBarTrack.setGeometry(QtCore.QRect(56, 205, 413, 10))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.progressBarTrack.setFont(font)
        self.progressBarTrack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.progressBarTrack.setProperty("value", 0)
        self.progressBarTrack.setFormat(_fromUtf8(""))
        self.progressBarTrack.setObjectName(_fromUtf8("progressBarTrack"))
        self.DepartureImage = QtGui.QLabel(self.centralwidget)
        self.DepartureImage.setGeometry(QtCore.QRect(30, 198, 31, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.DepartureImage.setFont(font)
        self.DepartureImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DepartureImage.setText(_fromUtf8(""))
        self.DepartureImage.setObjectName(_fromUtf8("DepartureImage"))
        self.DestinationImage = QtGui.QLabel(self.centralwidget)
        self.DestinationImage.setGeometry(QtCore.QRect(441, 198, 31, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.DestinationImage.setFont(font)
        self.DestinationImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DestinationImage.setText(_fromUtf8(""))
        self.DestinationImage.setObjectName(_fromUtf8("DestinationImage"))
        self.Departure_Info = QtGui.QLabel(self.centralwidget)
        self.Departure_Info.setGeometry(QtCore.QRect(15, 103, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Departure_Info.setFont(font)
        self.Departure_Info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Departure_Info.setText(QtGui.QApplication.translate("QPilotInfo", "Departure", None, QtGui.QApplication.UnicodeUTF8))
        self.Departure_Info.setObjectName(_fromUtf8("Departure_Info"))
        self.Destination_Info = QtGui.QLabel(self.centralwidget)
        self.Destination_Info.setGeometry(QtCore.QRect(256, 103, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Destination_Info.setFont(font)
        self.Destination_Info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Destination_Info.setText(QtGui.QApplication.translate("QPilotInfo", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.Destination_Info.setObjectName(_fromUtf8("Destination_Info"))
        self.DepartureText = QtGui.QLabel(self.centralwidget)
        self.DepartureText.setGeometry(QtCore.QRect(15, 118, 231, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.DepartureText.setFont(font)
        self.DepartureText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DepartureText.setText(_fromUtf8(""))
        self.DepartureText.setObjectName(_fromUtf8("DepartureText"))
        self.DestinationText = QtGui.QLabel(self.centralwidget)
        self.DestinationText.setGeometry(QtCore.QRect(256, 118, 231, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.DestinationText.setFont(font)
        self.DestinationText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DestinationText.setText(_fromUtf8(""))
        self.DestinationText.setObjectName(_fromUtf8("DestinationText"))
        self.RouteText = QtGui.QTextEdit(self.centralwidget)
        self.RouteText.setGeometry(QtCore.QRect(11, 288, 476, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.RouteText.setFont(font)
        self.RouteText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RouteText.setReadOnly(True)
        self.RouteText.setAcceptRichText(False)
        self.RouteText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.RouteText.setObjectName(_fromUtf8("RouteText"))
        self.Route_label = QtGui.QLabel(self.centralwidget)
        self.Route_label.setGeometry(QtCore.QRect(13, 270, 41, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Route_label.setFont(font)
        self.Route_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Route_label.setText(QtGui.QApplication.translate("QPilotInfo", "Route", None, QtGui.QApplication.UnicodeUTF8))
        self.Route_label.setObjectName(_fromUtf8("Route_label"))
        self.AddFriend = QtGui.QPushButton(self.centralwidget)
        self.AddFriend.setGeometry(QtCore.QRect(150, 507, 99, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.AddFriend.setFont(font)
        self.AddFriend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddFriend.setText(QtGui.QApplication.translate("QPilotInfo", "Add Friend", None, QtGui.QApplication.UnicodeUTF8))
        self.AddFriend.setObjectName(_fromUtf8("AddFriend"))
        self.Close = QtGui.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(255, 507, 99, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.Close.setFont(font)
        self.Close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close.setText(QtGui.QApplication.translate("QPilotInfo", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setObjectName(_fromUtf8("Close"))
        self.GroundSpeed_label = QtGui.QLabel(self.centralwidget)
        self.GroundSpeed_label.setGeometry(QtCore.QRect(205, 227, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.GroundSpeed_label.setFont(font)
        self.GroundSpeed_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GroundSpeed_label.setText(QtGui.QApplication.translate("QPilotInfo", "Ground Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.GroundSpeed_label.setObjectName(_fromUtf8("GroundSpeed_label"))
        self.GroundSpeedNumber = QtGui.QLabel(self.centralwidget)
        self.GroundSpeedNumber.setGeometry(QtCore.QRect(299, 225, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.GroundSpeedNumber.setFont(font)
        self.GroundSpeedNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GroundSpeedNumber.setText(_fromUtf8(""))
        self.GroundSpeedNumber.setObjectName(_fromUtf8("GroundSpeedNumber"))
        self.AltitudeNumber = QtGui.QLabel(self.centralwidget)
        self.AltitudeNumber.setGeometry(QtCore.QRect(436, 225, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.AltitudeNumber.setFont(font)
        self.AltitudeNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AltitudeNumber.setText(_fromUtf8(""))
        self.AltitudeNumber.setObjectName(_fromUtf8("AltitudeNumber"))
        self.Altitude_label = QtGui.QLabel(self.centralwidget)
        self.Altitude_label.setGeometry(QtCore.QRect(375, 227, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Altitude_label.setFont(font)
        self.Altitude_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Altitude_label.setText(QtGui.QApplication.translate("QPilotInfo", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.Altitude_label.setObjectName(_fromUtf8("Altitude_label"))
        self.FlightStatusDetail = QtGui.QLabel(self.centralwidget)
        self.FlightStatusDetail.setGeometry(QtCore.QRect(105, 225, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.FlightStatusDetail.setFont(font)
        self.FlightStatusDetail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FlightStatusDetail.setText(_fromUtf8(""))
        self.FlightStatusDetail.setObjectName(_fromUtf8("FlightStatusDetail"))
        self.FlightStatus_label = QtGui.QLabel(self.centralwidget)
        self.FlightStatus_label.setGeometry(QtCore.QRect(16, 227, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.FlightStatus_label.setFont(font)
        self.FlightStatus_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FlightStatus_label.setText(QtGui.QApplication.translate("QPilotInfo", "Flight Status", None, QtGui.QApplication.UnicodeUTF8))
        self.FlightStatus_label.setObjectName(_fromUtf8("FlightStatus_label"))
        self.PilotNameText = QtGui.QLabel(self.centralwidget)
        self.PilotNameText.setGeometry(QtCore.QRect(13, 23, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.PilotNameText.setFont(font)
        self.PilotNameText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PilotNameText.setText(_fromUtf8(""))
        self.PilotNameText.setObjectName(_fromUtf8("PilotNameText"))
        self.Home = QtGui.QLabel(self.centralwidget)
        self.Home.setGeometry(QtCore.QRect(314, 25, 41, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Home.setFont(font)
        self.Home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Home.setText(QtGui.QApplication.translate("QPilotInfo", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.Home.setObjectName(_fromUtf8("Home"))
        self.HomeFlag = QtGui.QLabel(self.centralwidget)
        self.HomeFlag.setGeometry(QtCore.QRect(360, 21, 41, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.HomeFlag.setFont(font)
        self.HomeFlag.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HomeFlag.setText(_fromUtf8(""))
        self.HomeFlag.setObjectName(_fromUtf8("HomeFlag"))
        self.airline_image = QtGui.QLabel(self.centralwidget)
        self.airline_image.setGeometry(QtCore.QRect(195, 51, 111, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.airline_image.setFont(font)
        self.airline_image.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.airline_image.setText(_fromUtf8(""))
        self.airline_image.setObjectName(_fromUtf8("airline_image"))
        self.PobText = QtGui.QLabel(self.centralwidget)
        self.PobText.setGeometry(QtCore.QRect(157, 461, 51, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.PobText.setFont(font)
        self.PobText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PobText.setText(_fromUtf8(""))
        self.PobText.setObjectName(_fromUtf8("PobText"))
        self.TransponderText = QtGui.QLabel(self.centralwidget)
        self.TransponderText.setGeometry(QtCore.QRect(357, 460, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.TransponderText.setFont(font)
        self.TransponderText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TransponderText.setText(_fromUtf8(""))
        self.TransponderText.setObjectName(_fromUtf8("TransponderText"))
        self.TransponderLabel = QtGui.QLabel(self.centralwidget)
        self.TransponderLabel.setGeometry(QtCore.QRect(270, 462, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.TransponderLabel.setFont(font)
        self.TransponderLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TransponderLabel.setText(QtGui.QApplication.translate("QPilotInfo", "Transponder", None, QtGui.QApplication.UnicodeUTF8))
        self.TransponderLabel.setObjectName(_fromUtf8("TransponderLabel"))
        self.POBLabel = QtGui.QLabel(self.centralwidget)
        self.POBLabel.setGeometry(QtCore.QRect(16, 463, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.POBLabel.setFont(font)
        self.POBLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.POBLabel.setText(QtGui.QApplication.translate("QPilotInfo", "Passengers on Board", None, QtGui.QApplication.UnicodeUTF8))
        self.POBLabel.setObjectName(_fromUtf8("POBLabel"))
        self.AirplaneLabel = QtGui.QLabel(self.centralwidget)
        self.AirplaneLabel.setGeometry(QtCore.QRect(16, 428, 70, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.AirplaneLabel.setFont(font)
        self.AirplaneLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AirplaneLabel.setText(QtGui.QApplication.translate("QPilotInfo", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.AirplaneLabel.setObjectName(_fromUtf8("AirplaneLabel"))
        self.AirplaneText = QtGui.QLabel(self.centralwidget)
        self.AirplaneText.setGeometry(QtCore.QRect(17, 440, 461, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.AirplaneText.setFont(font)
        self.AirplaneText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AirplaneText.setText(_fromUtf8(""))
        self.AirplaneText.setObjectName(_fromUtf8("AirplaneText"))
        self.vid_label = QtGui.QLabel(self.centralwidget)
        self.vid_label.setGeometry(QtCore.QRect(210, 25, 21, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.vid_label.setFont(font)
        self.vid_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vid_label.setText(QtGui.QApplication.translate("QPilotInfo", "VID", None, QtGui.QApplication.UnicodeUTF8))
        self.vid_label.setObjectName(_fromUtf8("vid_label"))
        self.vidText = QtGui.QLabel(self.centralwidget)
        self.vidText.setGeometry(QtCore.QRect(237, 25, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.vidText.setFont(font)
        self.vidText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vidText.setText(_fromUtf8(""))
        self.vidText.setObjectName(_fromUtf8("vidText"))
        self.nauticalmiles = QtGui.QLabel(self.centralwidget)
        self.nauticalmiles.setGeometry(QtCore.QRect(110, 181, 281, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.nauticalmiles.setFont(font)
        self.nauticalmiles.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nauticalmiles.setText(_fromUtf8(""))
        self.nauticalmiles.setAlignment(QtCore.Qt.AlignCenter)
        self.nauticalmiles.setObjectName(_fromUtf8("nauticalmiles"))
        self.Altern_Airport_Text = QtGui.QLabel(self.centralwidget)
        self.Altern_Airport_Text.setGeometry(QtCore.QRect(15, 160, 231, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.Altern_Airport_Text.setFont(font)
        self.Altern_Airport_Text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Altern_Airport_Text.setText(_fromUtf8(""))
        self.Altern_Airport_Text.setObjectName(_fromUtf8("Altern_Airport_Text"))
        self.Altern_Airport = QtGui.QLabel(self.centralwidget)
        self.Altern_Airport.setGeometry(QtCore.QRect(15, 146, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Altern_Airport.setFont(font)
        self.Altern_Airport.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Altern_Airport.setText(QtGui.QApplication.translate("QPilotInfo", "Altern Airport 1", None, QtGui.QApplication.UnicodeUTF8))
        self.Altern_Airport.setObjectName(_fromUtf8("Altern_Airport"))
        self.Altern_Airport_Text_2 = QtGui.QLabel(self.centralwidget)
        self.Altern_Airport_Text_2.setGeometry(QtCore.QRect(256, 160, 231, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.Altern_Airport_Text_2.setFont(font)
        self.Altern_Airport_Text_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Altern_Airport_Text_2.setText(_fromUtf8(""))
        self.Altern_Airport_Text_2.setObjectName(_fromUtf8("Altern_Airport_Text_2"))
        self.Altern_Airport_2 = QtGui.QLabel(self.centralwidget)
        self.Altern_Airport_2.setGeometry(QtCore.QRect(256, 146, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Altern_Airport_2.setFont(font)
        self.Altern_Airport_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Altern_Airport_2.setText(QtGui.QApplication.translate("QPilotInfo", "Altern Airport 2", None, QtGui.QApplication.UnicodeUTF8))
        self.Altern_Airport_2.setObjectName(_fromUtf8("Altern_Airport_2"))
        self.AccordingFP = QtGui.QLabel(self.centralwidget)
        self.AccordingFP.setGeometry(QtCore.QRect(16, 247, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.AccordingFP.setFont(font)
        self.AccordingFP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AccordingFP.setText(QtGui.QApplication.translate("QPilotInfo", "According Flight Plan", None, QtGui.QApplication.UnicodeUTF8))
        self.AccordingFP.setObjectName(_fromUtf8("AccordingFP"))
        self.GroupDetails = QtGui.QGroupBox(self.centralwidget)
        self.GroupDetails.setGeometry(QtCore.QRect(4, 90, 491, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.GroupDetails.setFont(font)
        self.GroupDetails.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GroupDetails.setTitle(QtGui.QApplication.translate("QPilotInfo", "Flight Details", None, QtGui.QApplication.UnicodeUTF8))
        self.GroupDetails.setObjectName(_fromUtf8("GroupDetails"))
        self.PilotDetails = QtGui.QGroupBox(self.centralwidget)
        self.PilotDetails.setGeometry(QtCore.QRect(4, 10, 491, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.PilotDetails.setFont(font)
        self.PilotDetails.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PilotDetails.setTitle(QtGui.QApplication.translate("QPilotInfo", "Pilot in Command", None, QtGui.QApplication.UnicodeUTF8))
        self.PilotDetails.setObjectName(_fromUtf8("PilotDetails"))
        self.Aircraft = QtGui.QGroupBox(self.centralwidget)
        self.Aircraft.setGeometry(QtCore.QRect(4, 416, 491, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Aircraft.setFont(font)
        self.Aircraft.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Aircraft.setTitle(QtGui.QApplication.translate("QPilotInfo", "Aircraft", None, QtGui.QApplication.UnicodeUTF8))
        self.Aircraft.setObjectName(_fromUtf8("Aircraft"))
        self.Airline = QtGui.QLabel(self.centralwidget)
        self.Airline.setGeometry(QtCore.QRect(150, 55, 41, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Airline.setFont(font)
        self.Airline.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Airline.setText(QtGui.QApplication.translate("QPilotInfo", "Airline", None, QtGui.QApplication.UnicodeUTF8))
        self.Airline.setObjectName(_fromUtf8("Airline"))
        self.GSFiled = QtGui.QLabel(self.centralwidget)
        self.GSFiled.setGeometry(QtCore.QRect(205, 248, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.GSFiled.setFont(font)
        self.GSFiled.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GSFiled.setText(QtGui.QApplication.translate("QPilotInfo", "GS (Filed)", None, QtGui.QApplication.UnicodeUTF8))
        self.GSFiled.setObjectName(_fromUtf8("GSFiled"))
        self.GSFiledText = QtGui.QLabel(self.centralwidget)
        self.GSFiledText.setGeometry(QtCore.QRect(271, 246, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.GSFiledText.setFont(font)
        self.GSFiledText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GSFiledText.setText(_fromUtf8(""))
        self.GSFiledText.setObjectName(_fromUtf8("GSFiledText"))
        self.FLText = QtGui.QLabel(self.centralwidget)
        self.FLText.setGeometry(QtCore.QRect(441, 245, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.FLText.setFont(font)
        self.FLText.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FLText.setText(_fromUtf8(""))
        self.FLText.setObjectName(_fromUtf8("FLText"))
        self.FLFiled = QtGui.QLabel(self.centralwidget)
        self.FLFiled.setGeometry(QtCore.QRect(375, 248, 61, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.FLFiled.setFont(font)
        self.FLFiled.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FLFiled.setText(QtGui.QApplication.translate("QPilotInfo", "FL (Filed)", None, QtGui.QApplication.UnicodeUTF8))
        self.FLFiled.setObjectName(_fromUtf8("FLFiled"))
        QPilotInfo.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(QPilotInfo)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        QPilotInfo.setStatusBar(self.statusBar)

        self.retranslateUi(QPilotInfo)
        QtCore.QObject.connect(self.Close, QtCore.SIGNAL(_fromUtf8("clicked()")), QPilotInfo.close)
        QtCore.QMetaObject.connectSlotsByName(QPilotInfo)

    def retranslateUi(self, QPilotInfo):
        pass

