# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/PlayerInfoWindow_UI.ui'
#
# Created: Tue Sep  6 15:57:02 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QPlayerInfo(object):
    def setupUi(self, QPlayerInfo):
        QPlayerInfo.setObjectName(_fromUtf8("QPlayerInfo"))
        QPlayerInfo.setWindowModality(QtCore.Qt.NonModal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QPlayerInfo.sizePolicy().hasHeightForWidth())
        QPlayerInfo.setSizePolicy(sizePolicy)
        QPlayerInfo.setMinimumSize(QtCore.QSize(491, 360))
        QPlayerInfo.setMaximumSize(QtCore.QSize(491, 360))
        QPlayerInfo.setCursor(QtCore.Qt.PointingHandCursor)
        self.centralwidget = QtGui.QWidget(QPlayerInfo)
        self.centralwidget.setCursor(QtCore.Qt.PointingHandCursor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.callsign_label = QtGui.QLabel(self.centralwidget)
        self.callsign_label.setGeometry(QtCore.QRect(10, 17, 57, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.callsign_label.setFont(font)
        self.callsign_label.setCursor(QtCore.Qt.PointingHandCursor)
        self.callsign_label.setObjectName(_fromUtf8("callsign_label"))
        self.airline_image = QtGui.QLabel(self.centralwidget)
        self.airline_image.setGeometry(QtCore.QRect(70, 12, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.airline_image.setFont(font)
        self.airline_image.setCursor(QtCore.Qt.PointingHandCursor)
        self.airline_image.setText(_fromUtf8(""))
        self.airline_image.setObjectName(_fromUtf8("airline_image"))
        self.rating_img = QtGui.QLabel(self.centralwidget)
        self.rating_img.setGeometry(QtCore.QRect(310, 12, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rating_img.setFont(font)
        self.rating_img.setCursor(QtCore.Qt.PointingHandCursor)
        self.rating_img.setText(_fromUtf8(""))
        self.rating_img.setObjectName(_fromUtf8("rating_img"))
        self.rating_label = QtGui.QLabel(self.centralwidget)
        self.rating_label.setGeometry(QtCore.QRect(253, 17, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rating_label.setFont(font)
        self.rating_label.setCursor(QtCore.Qt.PointingHandCursor)
        self.rating_label.setObjectName(_fromUtf8("rating_label"))
        self.progressBarTrack = QtGui.QProgressBar(self.centralwidget)
        self.progressBarTrack.setGeometry(QtCore.QRect(56, 148, 381, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.progressBarTrack.setFont(font)
        self.progressBarTrack.setCursor(QtCore.Qt.PointingHandCursor)
        self.progressBarTrack.setProperty(_fromUtf8("value"), 0)
        self.progressBarTrack.setFormat(_fromUtf8(""))
        self.progressBarTrack.setObjectName(_fromUtf8("progressBarTrack"))
        self.DepartureImage = QtGui.QLabel(self.centralwidget)
        self.DepartureImage.setGeometry(QtCore.QRect(20, 140, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DepartureImage.setFont(font)
        self.DepartureImage.setCursor(QtCore.Qt.PointingHandCursor)
        self.DepartureImage.setText(_fromUtf8(""))
        self.DepartureImage.setObjectName(_fromUtf8("DepartureImage"))
        self.DestinationImage = QtGui.QLabel(self.centralwidget)
        self.DestinationImage.setGeometry(QtCore.QRect(441, 140, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DestinationImage.setFont(font)
        self.DestinationImage.setCursor(QtCore.Qt.PointingHandCursor)
        self.DestinationImage.setText(_fromUtf8(""))
        self.DestinationImage.setObjectName(_fromUtf8("DestinationImage"))
        self.Departure_Info = QtGui.QLabel(self.centralwidget)
        self.Departure_Info.setGeometry(QtCore.QRect(10, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Departure_Info.setFont(font)
        self.Departure_Info.setCursor(QtCore.Qt.PointingHandCursor)
        self.Departure_Info.setObjectName(_fromUtf8("Departure_Info"))
        self.Destination_Info = QtGui.QLabel(self.centralwidget)
        self.Destination_Info.setGeometry(QtCore.QRect(253, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Destination_Info.setFont(font)
        self.Destination_Info.setCursor(QtCore.Qt.PointingHandCursor)
        self.Destination_Info.setObjectName(_fromUtf8("Destination_Info"))
        self.DepartureText = QtGui.QLabel(self.centralwidget)
        self.DepartureText.setGeometry(QtCore.QRect(10, 90, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DepartureText.setFont(font)
        self.DepartureText.setCursor(QtCore.Qt.PointingHandCursor)
        self.DepartureText.setText(_fromUtf8(""))
        self.DepartureText.setObjectName(_fromUtf8("DepartureText"))
        self.DestinationText = QtGui.QLabel(self.centralwidget)
        self.DestinationText.setGeometry(QtCore.QRect(253, 90, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DestinationText.setFont(font)
        self.DestinationText.setCursor(QtCore.Qt.PointingHandCursor)
        self.DestinationText.setText(_fromUtf8(""))
        self.DestinationText.setObjectName(_fromUtf8("DestinationText"))
        self.FlightPlanText = QtGui.QTextEdit(self.centralwidget)
        self.FlightPlanText.setGeometry(QtCore.QRect(8, 195, 476, 111))
        self.FlightPlanText.setObjectName(_fromUtf8("FlightPlanText"))
        self.FlightPlan_label = QtGui.QLabel(self.centralwidget)
        self.FlightPlan_label.setGeometry(QtCore.QRect(10, 175, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.FlightPlan_label.setFont(font)
        self.FlightPlan_label.setCursor(QtCore.Qt.PointingHandCursor)
        self.FlightPlan_label.setObjectName(_fromUtf8("FlightPlan_label"))
        self.AddFriend = QtGui.QPushButton(self.centralwidget)
        self.AddFriend.setGeometry(QtCore.QRect(88, 320, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AddFriend.setFont(font)
        self.AddFriend.setCursor(QtCore.Qt.PointingHandCursor)
        self.AddFriend.setObjectName(_fromUtf8("AddFriend"))
        self.ShowMap = QtGui.QPushButton(self.centralwidget)
        self.ShowMap.setGeometry(QtCore.QRect(198, 320, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ShowMap.setFont(font)
        self.ShowMap.setCursor(QtCore.Qt.PointingHandCursor)
        self.ShowMap.setObjectName(_fromUtf8("ShowMap"))
        self.Close = QtGui.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(308, 320, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Close.setFont(font)
        self.Close.setCursor(QtCore.Qt.PointingHandCursor)
        self.Close.setObjectName(_fromUtf8("Close"))
        QPlayerInfo.setCentralWidget(self.centralwidget)

        self.retranslateUi(QPlayerInfo)
        QtCore.QMetaObject.connectSlotsByName(QPlayerInfo)

    def retranslateUi(self, QPlayerInfo):
        QPlayerInfo.setWindowTitle(QtGui.QApplication.translate("QPlayerInfo", "Info of Player", None, QtGui.QApplication.UnicodeUTF8))
        self.callsign_label.setText(QtGui.QApplication.translate("QPlayerInfo", "Callsign", None, QtGui.QApplication.UnicodeUTF8))
        self.rating_label.setText(QtGui.QApplication.translate("QPlayerInfo", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.Departure_Info.setText(QtGui.QApplication.translate("QPlayerInfo", "Departure", None, QtGui.QApplication.UnicodeUTF8))
        self.Destination_Info.setText(QtGui.QApplication.translate("QPlayerInfo", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.FlightPlan_label.setText(QtGui.QApplication.translate("QPlayerInfo", "Flight Plan", None, QtGui.QApplication.UnicodeUTF8))
        self.AddFriend.setText(QtGui.QApplication.translate("QPlayerInfo", "Add Friend", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowMap.setText(QtGui.QApplication.translate("QPlayerInfo", "Show in Map", None, QtGui.QApplication.UnicodeUTF8))
        self.Close.setText(QtGui.QApplication.translate("QPlayerInfo", "Close", None, QtGui.QApplication.UnicodeUTF8))

