# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/SettingWindow_UI.ui'
#
# Created: Wed Sep  7 12:41:00 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName(_fromUtf8("SettingWindow"))
        SettingWindow.resize(320, 290)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingWindow.sizePolicy().hasHeightForWidth())
        SettingWindow.setSizePolicy(sizePolicy)
        SettingWindow.setMinimumSize(QtCore.QSize(320, 290))
        SettingWindow.setMaximumSize(QtCore.QSize(320, 290))
        SettingWindow.setCursor(QtCore.Qt.PointingHandCursor)
        SettingWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(SettingWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SettingAccepButton = QtGui.QPushButton(self.centralwidget)
        self.SettingAccepButton.setGeometry(QtCore.QRect(108, 260, 99, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SettingAccepButton.setFont(font)
        self.SettingAccepButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.SettingAccepButton.setObjectName(_fromUtf8("SettingAccepButton"))
        self.SettingTimeUpdate = QtGui.QLabel(self.centralwidget)
        self.SettingTimeUpdate.setGeometry(QtCore.QRect(14, 16, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SettingTimeUpdate.setFont(font)
        self.SettingTimeUpdate.setCursor(QtCore.Qt.PointingHandCursor)
        self.SettingTimeUpdate.setObjectName(_fromUtf8("SettingTimeUpdate"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(250, 13, 56, 22))
        self.spinBox.setCursor(QtCore.Qt.PointingHandCursor)
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(60)
        self.spinBox.setSingleStep(5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.Setting_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.Setting_checkBox.setGeometry(QtCore.QRect(14, 46, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Setting_checkBox.setFont(font)
        self.Setting_checkBox.setCursor(QtCore.Qt.PointingHandCursor)
        self.Setting_checkBox.setChecked(False)
        self.Setting_checkBox.setTristate(False)
        self.Setting_checkBox.setObjectName(_fromUtf8("Setting_checkBox"))
        self.proxy_host = QtGui.QLabel(self.centralwidget)
        self.proxy_host.setEnabled(False)
        self.proxy_host.setGeometry(QtCore.QRect(20, 79, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.proxy_host.setFont(font)
        self.proxy_host.setCursor(QtCore.Qt.PointingHandCursor)
        self.proxy_host.setObjectName(_fromUtf8("proxy_host"))
        self.proxy_port = QtGui.QLabel(self.centralwidget)
        self.proxy_port.setEnabled(False)
        self.proxy_port.setGeometry(QtCore.QRect(60, 103, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.proxy_port.setFont(font)
        self.proxy_port.setCursor(QtCore.Qt.PointingHandCursor)
        self.proxy_port.setObjectName(_fromUtf8("proxy_port"))
        self.proxy_user = QtGui.QLabel(self.centralwidget)
        self.proxy_user.setEnabled(False)
        self.proxy_user.setGeometry(QtCore.QRect(30, 178, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.proxy_user.setFont(font)
        self.proxy_user.setCursor(QtCore.Qt.PointingHandCursor)
        self.proxy_user.setObjectName(_fromUtf8("proxy_user"))
        self.proxy_pass = QtGui.QLabel(self.centralwidget)
        self.proxy_pass.setEnabled(False)
        self.proxy_pass.setGeometry(QtCore.QRect(31, 205, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.proxy_pass.setFont(font)
        self.proxy_pass.setCursor(QtCore.Qt.PointingHandCursor)
        self.proxy_pass.setObjectName(_fromUtf8("proxy_pass"))
        self.Setting_auth = QtGui.QCheckBox(self.centralwidget)
        self.Setting_auth.setEnabled(False)
        self.Setting_auth.setGeometry(QtCore.QRect(14, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Setting_auth.setFont(font)
        self.Setting_auth.setCursor(QtCore.Qt.PointingHandCursor)
        self.Setting_auth.setChecked(False)
        self.Setting_auth.setTristate(False)
        self.Setting_auth.setObjectName(_fromUtf8("Setting_auth"))
        self.lineEdit_host = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_host.setEnabled(False)
        self.lineEdit_host.setGeometry(QtCore.QRect(90, 75, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_host.setFont(font)
        self.lineEdit_host.setObjectName(_fromUtf8("lineEdit_host"))
        self.lineEdit_port = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_port.setEnabled(False)
        self.lineEdit_port.setGeometry(QtCore.QRect(90, 100, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_port.setFont(font)
        self.lineEdit_port.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_port.setMaxLength(5)
        self.lineEdit_port.setObjectName(_fromUtf8("lineEdit_port"))
        self.lineEdit_user = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_user.setEnabled(False)
        self.lineEdit_user.setGeometry(QtCore.QRect(90, 175, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setObjectName(_fromUtf8("lineEdit_user"))
        self.lineEdit_pass = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_pass.setEnabled(False)
        self.lineEdit_pass.setGeometry(QtCore.QRect(90, 201, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_pass.setObjectName(_fromUtf8("lineEdit_pass"))
        SettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        SettingWindow.setWindowTitle(QtGui.QApplication.translate("SettingWindow", "Settings of IVAO :: Status", None, QtGui.QApplication.UnicodeUTF8))
        self.SettingAccepButton.setText(QtGui.QApplication.translate("SettingWindow", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.SettingTimeUpdate.setText(QtGui.QApplication.translate("SettingWindow", "Setting Time for Update Info in minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.Setting_checkBox.setText(QtGui.QApplication.translate("SettingWindow", "Use Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_host.setText(QtGui.QApplication.translate("SettingWindow", "Host  http://", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_port.setText(QtGui.QApplication.translate("SettingWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_user.setText(QtGui.QApplication.translate("SettingWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.proxy_pass.setText(QtGui.QApplication.translate("SettingWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.Setting_auth.setText(QtGui.QApplication.translate("SettingWindow", "Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_port.setInputMask(QtGui.QApplication.translate("SettingWindow", "00000; ", None, QtGui.QApplication.UnicodeUTF8))

